#!/usr/bin/env bun
/**
 * Reads frontend/dist/ and writes frontend-bundle.generated.ts, which embeds
 * every file as base64. Imported by index.ts so that `bun build --compile`
 * includes the frontend inside the self-contained binary.
 *
 * Run after `pnpm --dir frontend build`.
 */
import { readdir, readFile } from "node:fs/promises";
import { extname, join } from "node:path";

const DIST_DIR = "./frontend/dist";
const OUTPUT = "./frontend-bundle.generated.ts";

const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".js": "application/javascript",
  ".mjs": "application/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".txt": "text/plain",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
};

interface Entry {
  path: string;
  mime: string;
  data: string;
}

async function walk(dir: string, prefix: string): Promise<Entry[]> {
  const results: Entry[] = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    const urlPath = `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      results.push(...(await walk(full, urlPath)));
    } else {
      const content = await readFile(full);
      results.push({
        path: urlPath,
        mime: MIME[extname(entry.name).toLowerCase()] ?? "application/octet-stream",
        data: content.toString("base64"),
      });
    }
  }
  return results;
}

const files = await walk(DIST_DIR, "");

const lines = files
  .map(
    (f) =>
      `  ${JSON.stringify(f.path)}: { mime: ${JSON.stringify(f.mime)}, data: ${JSON.stringify(f.data)} },`,
  )
  .join("\n");

await Bun.write(
  OUTPUT,
  `// AUTO-GENERATED by scripts/embed-frontend.ts — do not edit\nexport const frontendBundle: Record<string, { mime: string; data: string }> = {\n${lines}\n};\n`,
);

console.log(`Embedded ${files.length} files → ${OUTPUT}`);
